name: Java CI

on:
  push:
    branches: [ main, master ] # 建议限制分支，避免哪怕改个 README 的草稿分支也频繁触发 CI
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 使用最新的 checkout 版本
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Checkout dependent repo
        uses: actions/checkout@v4
        with:
          repository: 'yaolei313/apt-study'
          path: 'repo-b'

      # 使用最新的 setup-java 版本（支持 JDK 17 并且内置了缓存功能）
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install Dependent Jar
        run: mvn -B clean install --file repo-b/pom.xml

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml -Dmaven.test.skip=true